### ISSUE TITLE
Failed to load correctly (1.18.2)

### ISSUE THREAD

**Issue by vKILLZONEv** [SongXia-NYU/castle_in_the_sky#17]
Mod fails to load.  Here's the log:

[crash-2022-03-17_16.15.12-fml.txt](https://github.com/CarrotOfRivia/castle_in_the_sky/files/8291486/crash-2022-03-17_16.15.12-fml.txt)

**Comment by CarrotOfRivia** [comment]
1.18.1 is not compatible with 1.18.2.

1.18.2 version mod is out just now on curseforge, which should work with your modpack.
