### ISSUE TITLE
generate error

### ISSUE THREAD

**Issue by ghost** [SongXia-NYU/castle_in_the_sky#20]
structure is missing part

minecraft 1.18.2
forge 40.1.0
mod 0.4.1

8417 288 -5992

![image](https://user-images.githubusercontent.com/51057953/164014217-12507eff-57ce-488c-ac8e-35329af69e7d.png)

[World](https://drive.google.com/file/d/1saFnKcAENTU9t3aH67u7O-liIk5Xe_X7/view?usp=sharing)

**Comment by EvergreenSystems** [comment]
I can corroborate this, the structure generates missing one or more chunks-worth of the structure (or in one case just a singular chunk of the structure with the rest missing). This only seems to be an issue with version 0.4.1 of the mod

**Comment by CarrotOfRivia** [comment]
Thank you for the report. It is a tricky problem starting from Minecraft 1.18.2. I will try to fix it asap.

**Comment by Knocks83** [comment]
Hello! Just a ping: @CarrotOfRivia has the problem ever been fixed? I love your mod, but sadly the version I'm planning to use is 1.18.2. It would be a shame to not be able to use your mod due to the generation bug

**Comment by CarrotOfRivia** [comment]
Unfortunately no and there is no plan to fix the issue in 1.18.2 version since it is automatically fixed in 1.19.2.
