### ISSUE TITLE
Incomplete generation

### ISSUE THREAD

**Issue by greenleader11** [SongXia-NYU/castle_in_the_sky#21]
![2022-08-04_13 18 51](https://user-images.githubusercontent.com/110929972/183722575-c49bf79f-a67a-46ca-9ffe-f393b0d63865.png)
This is similar to another issue you're working on but I thought this might help. Using version 0.4.1, our first castle looked like this. Only one tiny chunk actually generated. We searched for another castle and it was also incomplete. It was a little bigger, but still less than half the total structure.

Not sure if this is plausible, but it might be nice to add the castle to the /placefeature command in 1.18

Great work on the mod, I hope we'll be able to explore the real thing soon. :)

**Comment by CarrotOfRivia** [comment]
Thanks for the report. This issue seems to be fixed in 1.19.2 version (mod version 0.5.1).
