### ISSUE TITLE
关于部分红石机关无法生效，以及触发某些东西时游戏崩溃

### ISSUE THREAD

**Issue by beimunans** [SongXia-NYU/castle_in_the_sky#24]
游戏1.18.2，Forge40.2.0，Mod0.4.1，已创建世界加入mod
部分红石机关无法生效
一层左手第一个蓝色房间通向城堡外的活塞门无法触发，检测为拉杆下的红石信号一直有且拉杆无法控制；终点房间的开门机关的红石信号在强度14的位置断开，创造模式破坏和放置红石粉时各有一次游戏崩溃，放置后仍然断开。
一二层的部分拉杆栏杆活塞门无法触发，拉杆无法控制红石信号。在试图触发射箭标靶开关时，箭矢射到标靶以外的地方会导致游戏崩溃。
三层的三蜘蛛刷怪笼第一次生成怪物时会导致游戏崩溃。
以上红石问题在创造模式修复时都会导致游戏崩溃，当前存档可复现，新世界除刷怪笼外可复现。
下方是游戏崩溃时启动器弹出的崩溃提示。
The game crashed whilst exception while updating neighbours
Error: java.lang.ClassCastException: class com.the_millman.waterlogged_redstone.common.blocks.RedStoneWireBlock cannot be cast to class net.minecraft.world.level.LevelAccessor (com.the_millman.waterlogged_redstone.common.blocks.RedStoneWireBlock is in module wlrs@1.13.0-1.18.2 of loader 'TRANSFORMER' @38e8488f; net.minecraft.world.level.LevelAccessor is in module minecraft@1.18.2 of loader 'TRANSFORMER' @38e8488f)

**Comment by SongXia-NYU** [comment]
您好，根据崩溃提示，游戏崩溃的原因来自于另外一个模组`com.the_millman.waterlogged_redstone`，请问你们有没有安装[Waterlogged Redstone](https://www.curseforge.com/minecraft/mc-mods/waterlogged-redstone)模组？
本模组城堡里面的红石使用的都是原版红石，导致游戏崩溃的可能性不是很大。

感谢您的反馈！

**Comment by beimunans** [comment]
不好意思，我的，是水下红石导致的崩溃和闪退
