### ISSUE TITLE
Request: Lootr Compat

### ISSUE THREAD

**Issue by VallenFrostweaver** [SongXia-NYU/castle_in_the_sky#4]
Minecraft 1.16.5
Forge 36.2.2
Castle In The Sky 0.2.6

I have added your wonderful mod to a pack and found that it did not have compat with Lootr and with the rarity of these structures the people on the server would love to have their own instanced loot when they explore it together! You would need to convert to the static setLootTable method instead of the tile entity method. Thank you.

**Comment by SongXia-NYU** [comment]
Thanks for the suggestion! I will definitely look into that.

**Comment by noobanidus** [comment]
I have recently updated the [Lootr documentation with a "For Developers" section](https://www.curseforge.com/minecraft/mc-mods/lootr). Please let me know if you need any further information on compatibility.

**Comment by EnterFor** [comment]
Oh, hopefully this will happen soon and I also hope they are compatible.

**Comment by EnterFor** [comment]
> Thanks for the suggestion! I will definitely look into that.

Hey, are you still going to deal with this? I can't wait......pls.....

**Comment by SongXia-NYU** [comment]
After reading the LootR page:
"If you manually create a chest and then fill its contents via your mod, without assigning a loot table, **your mod will not be compatible**."
Unfortunately, this is the case in my mod. So this mod is not compatible with LootR. Sorry for the wait.
