### ISSUE TITLE
Castle only loads in with 1/4 of blocks

### ISSUE THREAD

**Issue by WatchOuTx** [SongXia-NYU/castle_in_the_sky#5]
Hello, loaded your mod and found after 20 mins of flying your castle.
Was extremely happy about it until i found out that only 1/4 of the castle is in my world? how is that possible? is there any problems with known mods? 
using it in the 1.18 version, have some other mods installed but none that affect blocks or biomes beside repurposed structures mod.
is that a known bug, can i fix it somehow? cause this castle would be an amazing feature.

**Comment by SongXia-NYU** [comment]
Is it a new world or an existing world?

Could you save a copy of the save file to me (google drive or anything else)? 

Thanks for the report.

**Comment by WatchOuTx** [comment]
can i write you a private message or something? i am not that common with extracting save files or stuff like that^^

**Comment by SongXia-NYU** [comment]
Yeah. Send me massages on CurseForge.

**Comment by SongXia-NYU** [comment]
I found the same issue. It happens when the structure tries to generate on a wrong biome.

I am still trying to fix it.

Thank you for letting me know!

**Comment by Ideki** [comment]
I keep having the same issue.
Changing the distance from origin does not really fix it.
Do you have an idea when you will have a fix?
I am really looking forward to explore it.

**Comment by SongXia-NYU** [comment]
Fixed in 0.2.9
