### ISSUE TITLE
[1.16.5] Is this a mistake?

### ISSUE THREAD

**Issue by EnterFor** [SongXia-NYU/castle_in_the_sky#6]
I don't know why, when I deleted the module and started the server.
My background keeps spawning garbage logs.
![image](https://user-images.githubusercontent.com/10114685/147844375-27501f46-0449-45ad-810e-b06ddc9a57fd.png)
Is there a way around this?

**Comment by SongXia-NYU** [comment]
Looks like the structure is registered in the world before you remove the mod. I am not sure how to solve this issue but probably modifying/resetting level.dat might help.

**Comment by EnterFor** [comment]
There seems to be no good way to solve this problem
