### ISSUE TITLE
1.18.1 mod file set as 1.18

### ISSUE THREAD

**Issue by orionSquared** [SongXia-NYU/castle_in_the_sky#7]
Hello there,

I love your mod and I really want to add it to my vanilla plus pack, B'nilla, but your mod looks to be set for 1.18, not 1.18.1, so I can't add it on curseforge. And when I try to add it manually, curseforge rejects my pack. Can you just update the mod for 1.18.1 so I can add it please? I'd greatly appreciate it.

**Comment by SongXia-NYU** [comment]
Just uploaded 1.18.1 version which should be ready in a couple of hours.

Thank you for letting me know!

**Comment by orionSquared** [comment]
Thank you!!
