### ISSUE TITLE
Can you make the stone point to the new castle ?

### ISSUE THREAD

**Issue by blood789** [SongXia-NYU/castle_in_the_sky#8]
I already conquered the castle and bought another stone but it points to the same castle wasn't there to have more than one castle?

You can add some checks to the code to make the stone point to a new castle.

**Comment by SongXia-NYU** [comment]
The stone points to the nearest castle. You need to fly far away, deactivate it, re-activate it and it will point to a new one.

**Comment by blood789** [comment]
I just want to make a hardcore modpack.
And in the server, not all the player are op, not all the player can fly.........
It’s impossible for players to run tens of thousands of meters to find anothor one......
