### ISSUE TITLE
Crash on startup (java.lang.NoSuchFieldError: DIRT)

### ISSUE THREAD

**Issue by complicitsalami** [SongXia-NYU/castle_in_the_sky#9]
Have been enjoying this mod on the 1.18.1 version on our server, started running into this issue during startup recently.

Server crash report file:
https://paste-bin.xyz/31733

**Comment by complicitsalami** [comment]
I downgraded forge and the issue no longer occurs. Only happens when using the newest Forge version.

**Comment by SongXia-NYU** [comment]
Thank you for the report!
I will make it compatible to the newest Forge version in the future.

**Comment by Darkfiend009** [comment]
I just came to report this as well! Looks like someone beat me to it!

**Comment by SongXia-NYU** [comment]
Fixed in 0.2.9
